name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    #runs-on: ubuntu-22.04
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      IMAGE_NAME: lightning-hydra-add
      IMAGE_VERSION: ${{ github.sha }}

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ORG_GHCR_PAT }}

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Optional: Clean up Docker to free space
      # - name: Clean up Docker
      #   run: docker system prune -af

      # 5. Build and push Docker image with registry cache
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/cnsl-aisrc/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          cache-from: type=registry,ref=ghcr.io/cnsl-aisrc/${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=ghcr.io/cnsl-aisrc/${{ env.IMAGE_NAME }}:cache,mode=max
          # squash: true

      # 6. Optional: Add 'latest' tag
      - name: Tag latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker pull ghcr.io/cnsl-aisrc/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          docker tag ghcr.io/cnsl-aisrc/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} ghcr.io/cnsl-aisrc/${{ env.IMAGE_NAME }}:latest
          docker push ghcr.io/cnsl-aisrc/${{ env.IMAGE_NAME }}:latest
